name: GitHub-Profile-3D-Contrib

on:
  push:
    branches:
      - main
    paths:
      - 'settings/3dcontibs.json'
      - '.github/workflows/*'
  schedule:
    # every day at 18:00 UTC
    - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v4
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
          SETTING_JSON: 'settings/3dcontibs.json'
          MAX_REPOS: 500
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Update Profile 3D Contrib'
          commit_options: '--no-verify'
          commit_author: 'github-actions <41898282+github-actions[bot]@users.noreply.github.com>'
